#!/bin/bash

alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias glog='git glog'

alias visudo="sudo EDITOR=nvim visudo"
alias gcheat="curl cheat.sh/git"

alias bigf= 'find / -xdev -type f -size +500M'

alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index} > /dev/null"; unset index 

alias l='ls -l'
alias ll='ls -lahF'
alias lls='ls -lahFtr'
alias la='ls -A'
alias lc='ls -CF'

alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -iv'
alias la='ls -alh'

alias grep="grep -P -i --color=auto"
