#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — key ceremony for the tier-0 bootstrap kit.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

DOTFILES="${DOTFILES:-$HOME/sync/src/dotfiles}"
SECRETS="$DOTFILES/secrets"
RECIPIENTS="$SECRETS/recipients.txt"
KIT="$SECRETS/bootstrap.tar.age"
KITBIN="$DOTFILES/bin/bootstrap-kit"
WORKDIR=""   # tmpfs, set in the paper-key stage
PAPER_PUB=""
YKA_PUB=""
YKB_PUB=""
YKA_SERIAL=""
YKB_SERIAL=""

cleanup_tmpfs() {
  if [[ -n "$WORKDIR" && -d "$WORKDIR" ]]; then
    if findmnt -no TARGET "$WORKDIR" >/dev/null 2>&1; then
      sudo umount "$WORKDIR" 2>/dev/null || true
    fi
    rmdir "$WORKDIR" 2>/dev/null || true
  fi
}
trap cleanup_tmpfs EXIT

# The two keys are physically identical -- same model, same firmware. Only the
# SERIAL distinguishes them, so every operation is targeted by serial and the
# serials are recorded in recipients.txt. Otherwise you cannot later tell which
# physical key holds which identity.

# --serials prints bare integers; parsing the human-readable listing is fragile.
yk_serials() { ykman list --serials 2>/dev/null; }
yk_count()   { yk_serials | grep -c . ; }

# Recipient for one specific key. Never `tail -1` across keys: with two
# attached that silently returns the wrong one.
yk_recipient_for() {
  age-plugin-yubikey --list 2>/dev/null | grep -oE 'age1yubikey1[a-z0-9]+' | tail -1
}

# Read-only inventory of everything on a key, so the human can see the blast
# radius rather than take it on trust. Every command here is read-only and none
# consumes a PIN/PUK retry.
#
# Enrolment writes ONLY to PIV (retired slot 82) and sets ONLY the PIV
# PIN/PUK/management key. Applets keep independent credential stores, so OATH
# codes, the OTP slot, OpenPGP and FIDO2 are untouched.
key_inventory() {
  local serial=$1 n
  printf '  %sInventory of key %s%s\n' "$BOLD" "$serial" "$RESET"

  # OATH -- the applet most likely to hold real data (TOTP codes).
  local oath_pw
  oath_pw=$(timeout 15 ykman --device "$serial" oath info 2>/dev/null | grep -i 'Password protection' | awk -F': *' '{print $2}')
  local oath_list
  if oath_list=$(timeout 20 ykman --device "$serial" oath accounts list 2>/dev/null); then
    n=$(printf '%s' "$oath_list" | grep -c . || true)
    printf '    OATH/TOTP    %s credential(s), password protection: %s\n' "$n" "${oath_pw:-unknown}"
    [ "${n:-0}" -gt 0 ] && printf '%s\n' "$oath_list" | sed 's/^/                 - /'
  else
    n=0
    printf '    OATH/TOTP    could not read (password protected?)\n'
  fi
  [ "$oath_pw" = "disabled" ] && [ "${n:-0}" -gt 0 ] &&
    warn "OATH has no password: anyone holding this key can read those TOTP secrets"

  # Yubico OTP
  printf '    Yubico OTP   %s\n' "$(timeout 15 ykman --device "$serial" otp info 2>/dev/null | tr '\n' ' ' | sed 's/  */ /g')"

  # OpenPGP
  # ykman exits non-zero for an empty slot, and `set -o pipefail` would make
  # `ykman ... | grep -q` fail even when grep matched -- which reported every
  # empty slot as occupied. Capture the output, then test it.
  local pgp="" out
  for k in SIG DEC AUT; do
    out=$(timeout 12 ykman --device "$serial" openpgp keys info "$k" 2>&1 || true)
    case "$out" in *"No key stored"*) ;; *) pgp="$pgp $k" ;; esac
  done
  printf '    OpenPGP      %s\n' "${pgp:-empty}"

  # FIDO2
  printf '    FIDO2        PIN %s\n' "$(timeout 15 ykman --device "$serial" fido info 2>/dev/null | awk -F': *' '/^PIN/{print $2}')"

  # PIV -- the only applet enrolment touches.
  local occupied=""
  for sl in 9a 9c 9d 9e 82 83 84 85; do
    timeout 10 ykman --device "$serial" piv certificates export "$sl" - >/dev/null 2>&1 && occupied="$occupied $sl"
  done
  printf '    PIV          slots occupied:%s\n' "${occupied:- none}"
  timeout 15 ykman --device "$serial" piv info 2>/dev/null | grep -E 'PIN tries|PUK tries' | sed 's/^/                 /'
  if [ -n "$occupied" ]; then
    warn "PIV slots are NOT empty -- enrolling will overwrite slot 82 (plugin slot 1)"
  fi
  printf '\n'
  say "Enrolment writes ONLY to PIV slot 82 and sets ONLY the PIV PIN/PUK."
  say "OATH codes, the OTP slot, OpenPGP and FIDO2 are left alone."
}

# age-plugin-yubikey 0.5.x can panic on a DER "Overlength" while generating the
# random certificate serial -- reported at roughly half of all runs (upstream
# issue #220). Retry rather than aborting a ceremony that is not resumable.
# Slot is pinned explicitly: without --slot the plugin picks the first free
# retired slot, which makes the result depend on what was there before.
generate_identity() {
  local serial=$1 name=$2 attempt out rc
  for attempt in 1 2 3; do
    out=$(age-plugin-yubikey --generate --serial "$serial" --slot 1 \
            --pin-policy once --touch-policy always --name "$name" 2>&1 | tee /dev/tty)
    rc=${PIPESTATUS[0]}
    [ "$rc" -eq 0 ] && return 0

    # ONLY the #220 DER panic is safe to retry. Retrying anything else is
    # actively harmful: a wrong PIN decrements a 3-attempt counter, so a blind
    # retry loop blocks the key. That is exactly what happened here once.
    if printf '%s' "$out" | grep -qiE 'invalid pin|tries remaining|blocked'; then
      warn "wrong PIN -- NOT retrying (each attempt burns one of three tries)"
      printf '%s' "$out" | grep -oiE '[0-9]+ (try|tries) remaining' | tail -1 | sed 's/^/    /'
      say ""
      say "The prompt asks for the PIN ALREADY ON THE KEY, not a new one."
      say "On a factory key that is the default: 123456"
      say "If it is now blocked, unblock it with:"
      say "  ykman --device $serial piv access unblock-pin"
      return 1
    fi
    if printf '%s' "$out" | grep -qiE 'overlength|panic'; then
      warn "hit the known #220 generation panic on attempt $attempt - retrying"
      sleep 2
      continue
    fi
    warn "generation failed for an unrecognised reason - not retrying"
    return 1
  done
  return 1
}

# Block until EXACTLY one key is present, then echo its serial. Refusing to
# proceed with two attached is deliberate: --generate would be ambiguous, and
# you would not know which key you just touched.
# NOTE: this function RETURNS the serial on stdout, so every byte of progress
# output must go to stderr. Writing the spinner to stdout meant the caller
# captured "\r\033[K23610307" and passed that to --serial, which failed with
# "invalid digit found in string".
wait_for_exactly_one() {
  local n
  while true; do
    n=$(yk_count)
    if [[ "$n" == "1" ]]; then printf '\r\033[K' >&2; yk_serials; return 0; fi
    if [[ "$n" == "0" ]]; then
      printf '  %swaiting for a YubiKey to be INSERTED...%s\r' "$DIM" "$RESET" >&2
    else
      printf '  %s%s keys attached - leave only ONE plugged in...%s\r' "$YELLOW" "$n" "$RESET" >&2
    fi
    sleep 1
  done
}

# Block until a SPECIFIC serial is gone (others may remain).
wait_for_serial_gone() {
  local want=$1
  while yk_serials | grep -qx "$want"; do
    printf '  %swaiting for key %s to be REMOVED...%s\r' "$DIM" "$want" "$RESET" >&2
    sleep 1
  done
  printf '\r\033[K' >&2
}

# Deliberately NOT using the library's banner(): its stock text describes a
# browser-driven wizard and promises "re-run later — it remembers values already
# saved". Neither is true here, and the second is dangerous: a partial run can
# leave a key enrolled with no kit built, and re-running --generate overwrites a
# PIV slot. Say what actually happens instead.
_clear
printf '\n%s%s  YubiKey key ceremony — tier-0 bootstrap kit%s\n' "$BOLD" "$BLUE" "$RESET"
printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
say "You will be told exactly when to insert, remove and touch each key."
say "Nothing here uses a browser."
printf '\n'
warn "This ceremony is NOT resumable. Generating an identity overwrites that"
warn "PIV slot, so a half-finished run must be restarted deliberately."
printf '\n'
say "Have ready:"
step "both YubiKeys"
step "pen and paper (and a phone camera for the QR)"
step "somewhere offline to store the paper key"
printf '\n'
note "Takes about 10 minutes. Ctrl-C is safe until stage 2."
pause "Ready to start?"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the tools this ceremony needs. No key required yet."
for t in age age-plugin-yubikey ykman qrencode zbarimg; do
  if command -v "$t" >/dev/null 2>&1; then step "found $t"; else
    warn "missing $t — install it first (pacman -S age age-plugin-yubikey yubikey-manager qrencode zbar)"; exit 1
  fi
done
if systemctl is-active --quiet pcscd; then step "pcscd is running"; else
  warn "pcscd is not running — PIV will not work. Start it: sudo systemctl start pcscd"; exit 1
fi
[[ -x "$KITBIN" ]] || { warn "bootstrap-kit not found at $KITBIN"; exit 1; }
step "bootstrap-kit found"
if [[ -f "$KIT" ]]; then
  warn "A kit already exists at $KIT"
  confirm "Overwrite it at the end of this ceremony?" || { say "Nothing changed."; exit 0; }
fi
say ""
say "Blast radius: this ceremony writes ONLY to the PIV applet (retired slot 82)"
say "and sets ONLY the PIV PIN/PUK/management key. Applets have separate"
say "credential stores, so OATH/TOTP codes, the Yubico OTP slot, OpenPGP and"
say "FIDO2 are NOT touched. You will see a full inventory of each key before"
say "anything is written to it."
note "A full device reset (ykman config reset) WOULD destroy all of that -- this"
note "ceremony never does that."
say ""
note "PUK = PIN with this plugin: if you forget a key's PIN, that key is gone."
note "That is exactly why we enrol TWO keys plus a paper recovery key."
pause "Ready to begin?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Insert YubiKey A"
say "This generates an age identity on the key itself. The private key never"
say "leaves the hardware — only a public recipient comes back out."
warn "Leave ONLY YubiKey A plugged in (unplug the other one)."
YKA_SERIAL="$(wait_for_exactly_one)"
if [[ ! "$YKA_SERIAL" =~ ^[0-9]+$ ]]; then
  warn "got a non-numeric serial: $(printf '%q' "$YKA_SERIAL")"
  warn "this usually means progress output leaked into the captured value"
  exit 1
fi
step "detected YubiKey serial $YKA_SERIAL"
say ""
key_inventory "$YKA_SERIAL"
confirm "Enrol THIS key (PIV slot 82 only)?" || { say "Nothing written."; exit 0; }
say ""
warn "READ THIS: the prompt asks for the PIN ALREADY ON THE KEY."
say "It is NOT asking you to choose a new one."
say "  factory default: 123456"
say "  you get THREE attempts before the key blocks"
say ""
say "To use a PIN of your own, quit now (Ctrl-C) and set it first:"
say "  ykman --device $YKA_SERIAL piv access change-pin"
say ""
say "After the PIN, the key blinks for a touch."
say "Policy: --pin-policy once --touch-policy always (archival use, rare taps)."
pause "Press Enter, then follow the plugin's prompts"
generate_identity "$YKA_SERIAL" "bootstrap-A" || {
  warn "generation failed after retries — if slot 1 is filled, re-run with --force"; exit 1; }
YKA_PUB="$(yk_recipient_for)"
[[ "$YKA_PUB" =~ ^age1yubikey1[a-z0-9]+$ ]] || { warn "unexpected recipient: $YKA_PUB"; exit 1; }
[[ -n "$YKA_PUB" ]] || { warn "could not read a recipient from the key"; exit 1; }
step "YubiKey A ($YKA_SERIAL) recipient: $YKA_PUB"
pause "Recorded. Continue?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Swap to YubiKey B"
say "A second key means losing one is an inconvenience, not a lockout."
warn "REMOVE YubiKey A ($YKA_SERIAL) NOW."
wait_for_serial_gone "$YKA_SERIAL"
step "YubiKey A removed"
warn "INSERT YubiKey B NOW."
YKB_SERIAL="$(wait_for_exactly_one)"
if [[ ! "$YKB_SERIAL" =~ ^[0-9]+$ ]]; then
  warn "got a non-numeric serial: $(printf '%q' "$YKB_SERIAL")"; exit 1
fi
if [[ "$YKB_SERIAL" == "$YKA_SERIAL" ]]; then
  warn "that is the same key ($YKA_SERIAL) — insert the OTHER one"; exit 1
fi
step "detected YubiKey serial $YKB_SERIAL"
say ""
key_inventory "$YKB_SERIAL"
confirm "Enrol THIS key (PIV slot 82 only)?" || { say "Nothing written to key B."; exit 0; }
pause "Press Enter, then follow the plugin's prompts (PIN + touch)"
generate_identity "$YKB_SERIAL" "bootstrap-B" || {
  warn "generation failed after retries"; exit 1; }
YKB_PUB="$(yk_recipient_for)"
[[ "$YKB_PUB" =~ ^age1yubikey1[a-z0-9]+$ ]] || { warn "unexpected recipient: $YKB_PUB"; exit 1; }
[[ -n "$YKB_PUB" ]] || { warn "could not read a recipient from the key"; exit 1; }
[[ "$YKB_PUB" != "$YKA_PUB" ]] || { warn "same recipient as key A — is this the same key?"; exit 1; }
step "YubiKey B ($YKB_SERIAL) recipient: $YKB_PUB"
pause "Recorded. Continue?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Paper recovery key"
say "Last resort if both YubiKeys are lost. Generated in RAM with swap off so"
say "the private key never touches a disk."
WORKDIR="$(mktemp -d)"
sudo mount -t tmpfs -o size=16m,mode=700 tmpfs "$WORKDIR"
sudo chown "$USER" "$WORKDIR"
step "tmpfs mounted at $WORKDIR"
say ""
warn "Turning swap OFF while the key exists in memory (needs sudo)."
sudo swapoff -a
step "swap off"
( set +o history; age-keygen -o "$WORKDIR/paper.txt" 2>"$WORKDIR/paper.pub" )
PAPER_PUB="$(grep -oE 'age1[a-z0-9]+' "$WORKDIR/paper.pub" | head -1)"
qrencode -l H -o "$WORKDIR/paper.png" < "$WORKDIR/paper.txt"
_clear
printf '  %sWRITE THIS DOWN — it will not be shown again%s\n\n' "$BOLD$RED" "$RESET"
grep -v '^#' "$WORKDIR/paper.txt" | sed 's/^/    /'
printf '\n'
qrencode -t ANSIUTF8 -l H < "$WORKDIR/paper.txt"
printf '\n  %sRecipient (public, safe to keep anywhere):%s\n    %s\n\n' "$DIM" "$RESET" "$PAPER_PUB"
say "Write the text down AND photograph the QR. Store both offline (safe, not"
say "the same place as the YubiKeys, and not in a password manager you unlock"
say "with these keys)."
pause "Written down and stored? Press Enter to VERIFY it"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Verify the paper key"
say "Verifying the copy you just made actually works — BEFORE you rely on it."
say "This is the step people skip and regret."
step "scanning your QR back in to prove it is readable"
if zbarimg --raw -q "$WORKDIR/paper.png" > "$WORKDIR/scanned.txt" 2>/dev/null &&
   diff -q <(grep -v '^#' "$WORKDIR/paper.txt") <(grep -v '^#' "$WORKDIR/scanned.txt") >/dev/null; then
  step "QR round-trips correctly"
else
  warn "QR did NOT round-trip — do not rely on it. Keep the printed text."
fi
echo "canary $(date -Is)" > "$WORKDIR/canary.txt"
age -r "$PAPER_PUB" -o "$WORKDIR/canary.age" "$WORKDIR/canary.txt"
if age -d -i "$WORKDIR/paper.txt" "$WORKDIR/canary.age" >/dev/null 2>&1; then
  step "paper key decrypts a test file"
else
  warn "paper key FAILED to decrypt — aborting, something is wrong"; exit 1
fi
sudo swapon -a && step "swap back on"
pause "Paper key verified. Continue?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Update recipients"
say "Writing the three production recipients. The test recipients are removed:"
say "from here on, only your hardware and your paper key can open the kit."
cp "$RECIPIENTS" "$RECIPIENTS.bak.$(date +%Y%m%d%H%M%S)"
cat > "$RECIPIENTS" <<EOF
# age recipients for the tier-0 bootstrap kit.
#
# PUBLIC keys. Committing them is safe and intended -- the private half never
# leaves the YubiKey (or the paper backup). Any ONE of these can decrypt the
# kit, so losing a single factor is survivable.
#
# Enrolled $(date -Is) by scripts/enroll-yubikeys.sh
# Plugin: $(age-plugin-yubikey --version 2>/dev/null)

$YKA_PUB   yubikey-A  serial $YKA_SERIAL
$YKB_PUB   yubikey-B  serial $YKB_SERIAL
$PAPER_PUB   paper recovery (offline; generated on tmpfs with swap off)
EOF
step "wrote 3 recipients to $RECIPIENTS"
grep -vE '^\s*(#|$)' "$RECIPIENTS" | sed 's/^/    /'
pause "Continue to build the real kit?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Build the real kit"
say "Packing the paths in secrets/kit-manifest.txt and encrypting to all three."
say "This reads your REAL machine identity for the first time."
note "manifest: $SECRETS/kit-manifest.txt"
"$KITBIN" build -o "$KIT" || { warn "build failed"; exit 1; }
step "built $KIT"
stat -c '    %n  %s bytes  mode %a' "$KIT"
pause "Continue to the canary drill?"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Canary drill — prove every factor works"
say "Each factor must open the kit independently. If one cannot, you find out"
say "now rather than during a real recovery."
warn "Leave ONLY YubiKey A ($YKA_SERIAL) plugged in."
wait_for_exactly_one >/dev/null
say "Touch the key when it blinks."
if BOOTSTRAP_ADAPTER=yubikey "$KITBIN" verify "$KIT"; then step "YubiKey A opens the kit"; else
  warn "YubiKey A FAILED"; fi
warn "REMOVE YubiKey A ($YKA_SERIAL)."
wait_for_serial_gone "$YKA_SERIAL"
warn "INSERT YubiKey B ($YKB_SERIAL)."
wait_for_exactly_one >/dev/null
say "Touch the key when it blinks."
if BOOTSTRAP_ADAPTER=yubikey "$KITBIN" verify "$KIT"; then step "YubiKey B opens the kit"; else
  warn "YubiKey B FAILED"; fi
say ""
step "paper key was already verified against a canary in stage 5"
pause "Drill complete. Continue?"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Review and commit"
say "About to commit: public recipients + the encrypted kit. No private keys."
git -C "$DOTFILES" status --short -- secrets/ | sed 's/^/    /'
say ""
say "Sanity check — the kit must be ciphertext, and no private key may be staged:"
if grep -qa 'age-encryption.org' "$KIT"; then step "kit is a valid age file"; fi
# Literal split so this scanner does not trip the pre-commit hook's own
# private-key check on its own source.
if git -C "$DOTFILES" diff --cached 2>/dev/null | grep -q "AGE-SECRET-KEY""-1"; then
  warn "PRIVATE KEY STAGED — aborting"; exit 1
fi
step "no private key material staged"
if confirm "Commit and push the kit and recipients?"; then
  git -C "$DOTFILES" add secrets/recipients.txt "$KIT"
  git -C "$DOTFILES" commit -m "feat(secrets): enrol yubikeys, build real bootstrap kit" \
    -m "Recipients: YubiKey A, YubiKey B, offline paper key. Every factor verified
against the kit before committing. Test recipients removed." || true
  say "Committed. Push with: git -C $DOTFILES push"
else
  say "Left uncommitted. Review, then commit yourself."
fi

finish
